name: .NET Core CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1  # or the version you are using

    - name: Build and publish
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/app

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: $(Build.ArtifactStagingDirectory)/app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: app
        path: $(Build.ArtifactStagingDirectory)/app

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure subscription
      run: az account set --subscription <subscription-id>

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'demoquick'
        slot-name: 'production'  # or specify your deployment slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
